#!/usr/bin/env node

var fs = require('fs');

var path = require('path');
var projectRoot = path.resolve(__dirname);

var config = {};

var server = process.argv.slice(2)[0];

// apparently it only works by calling /api
// we replace /api with null when using proxy server
// the ApiClientService will keep track of the environment in order to add the additional /api before an actual endpoint
// npm run start uses the proxy config generated by this script and sets the env to dev
if (server) {
    config = {
        "/api": {
            "target": 'https://' + server,
            "secure": false,
            "changeOrigin": "true",
            "pathRewrite": {"^/api": ""}
        }
    }
}

fs.writeFile(projectRoot + "/proxy.conf.json", JSON.stringify(config, null, 2), function(err) {
    if(err) {
        return console.error(err);
    }
    if (server) {
        console.log("The proxy was set to " + server);
    } else {
        console.log("Proxy was removed")
    }
});